/**
 * Configuration constants for Floater Calculation
 */
const CONFIG = {
	// Sheet layout
	TITLE_ROW: 1,
	MONTH_ROW: 2,
	HEADER_ROW: 3,
	FIRST_DATA_ROW: 4,

	// Data columns
	EMP_ID_COL: 1, // Column A = Employee ID
	NAME_COL: 2, // Column B = Name
	DEPARTMENT_COL: 3, // Column C = Department
	FLOATER_PCT_COL: 4, // Column D = Floater %
	CURRENT_PROJECT_COL: 5, // Column E = Current Project

	// Total data columns
	DATA_COLS: 5,

	// Conditional Scales legend position
	LEGEND_START_COL: 7, // Column G
	LEGEND_LABEL_COL: 7, // Column G = Label
	LEGEND_COLOR_COL: 8, // Column H = Color swatch

	// Row highlight colors
	SCALES: {
		LEAVERS: { label: 'Leavers', color: '#D9D9D9', fontColor: '#000000' },
		NEW_JOINERS: { label: 'New Joiners', color: '#D9EAD3', fontColor: '#000000' },
	},

	// Header styling
	HEADER_BG: '#356854',
	HEADER_FONT_COLOR: '#FFFFFF',

	// Average salary for floater cost calculation (RM)
	AVERAGE_SALARY: 8000,

	// Source spreadsheet for project attendance data (read-only)
	// Reads from "[Month] [Year]" sheets (e.g. "February 2026") generated by google-appscript
	// Structure: A=ID, B=Name, C=Team, D=Project Contribution, E-J=formulas, K+=day columns (with Validated/Time off Override after each Friday)
	SOURCE_SPREADSHEET_ID: '1Ovem0aj5nU7FYyfGy9fgmy40psgHyJ9mq2UZdeu2G-s',

	// Employees to exclude (by exact full name)
	EXCLUDED_EMPLOYEES: ['Omni Support', 'People Culture'],

	// Teams to exclude from floater list (matched as substring, case-insensitive)
	// Operations team is not supposed to appear in the floater list
	EXCLUDED_TEAMS: ['operations'],
};
